// Sample inputs for previewing the notice layout before the Board has
// configured the sheet. Placeholder text is clearly marked as such and
// only ever reaches the /api/notices/sample route, never a real notice.

export const SAMPLE = {
  settings: {
    hoa_legal_name: 'Reserves at Park Creek Condominium Association',
    hoa_display_name: 'Reserves at Park Creek',
    management_company_name: '[Management Company — SAMPLE]',
    management_company_address: '[Street] • [City], MI [ZIP] — SAMPLE',
    management_company_tagline: '',
    manager_name: '[Manager Name — SAMPLE]',
    manager_email: 'manager@example.com',
  },
  rule: {
    id: 'RULE-008', name: 'Vehicular Parking / Storage',
    governing_document: '[Governing Document — SAMPLE]', governing_section: '[Section — SAMPLE]',
    governing_text: '[SAMPLE governing-document text. The Board-approved text from VIOLATION_RULES.governing_text will appear here; nothing is generated by the application.]',
    corrective_action_text: '[SAMPLE corrective action from VIOLATION_RULES.corrective_action_text.]',
  },
  property: { id: 'P1', property_address: '3482 Park Creek Lane' },
  owner: { name: 'Gregory and Andrea Hansen', email: 'sample@example.com', phone: '(555) 555-0100', mailing_address: '3482 Park Creek Lane', mailing_city: 'Canton', mailing_state: 'MI', mailing_zip: '48188' },
  violation: {
    id: 'V1', case_number: 'VIO-2026-0001', date_observed: '2026-09-15', offense_number: 2,
    description: 'Boat trailer parked in the driveway for more than 48 hours (sample description).',
    actual_deadline: '2026-09-29', default_deadline: '2026-09-29',
    owner_name_snapshot: 'Gregory and Andrea Hansen', owner_email_snapshot: 'sample@example.com',
    owner_mailing_snapshot: '3482 Park Creek Lane, Canton MI 48188',
  },
  event: { id: 'E1', step_number: 2, event_type: 'FINAL_WARNING', action_name: 'Final Warning', fine_amount: 0 },
}
